name: Deploy to Windows PC via SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, windows]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy files to target PC
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "."
          target: "C:/Users/${{ secrets.SSH_USER }}/docker-deploy"

      - name: Run deployment script on Windows PC
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd C:/Users/${{ secrets.SSH_USER }}/docker-deploy
            docker-compose down
            docker-compose up -d --build
